#security:
#    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
#
#    role_hierarchy:
#        ROLE_ADMIN:       [ROLE_USER, ROLE_API]
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
#
#    providers:
#        in_memory:
#            memory:
#                users:
#                    admin:  { password: admin, roles: [ 'ROLE_ADMIN' ] }
#                    test:  { password: test, roles: [ 'ROLE_USER' ] }
#
#    firewalls:
#        # doc:
#        #     pattern:  ^/doc
#        #     security: false
#
#        secured_area:
##            pattern:    ^/
##            stateless: true
#            #anonymous: ~
#            http_basic:
#               realm: "Secured Area"

    # access_control:
    #     - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
