auth:
  resource: "@PeekmoSfImmoBundle/Controller/AuthController.php"
  type: annotation

default:
  resource: "@PeekmoSfImmoBundle/Controller/DefaultController.php"
  type: annotation

admin:
  resource: "@PeekmoSfImmoBundle/Controller/AdminController.php"
  type: annotation